### ISSUE TITLE
Difficulty installing vpc

### ISSUE THREAD

**Issue by jmehta8** [ronkeizer/vpc#35]
Hi,
On an attempt to install vpc, I followed the below instructions, but end up getting error as described in 

install.packages("devtools")
library("devtools")
install_github("ronkeizer/vpc")
library(vpc)

Error

* installing *source* package 'vpc' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'e1071'
Error : package 'classInt' could not be loaded
ERROR: lazy loading failed for package 'vpc'
* removing 'C:/R-3.3.2/library/vpc'
Error: Command failed (1)

Kindly correct if I missed anything while installing.

Thank you,
~J

**Comment by ronkeizer** [comment]
can you try installing the missing packages e1071 and classInt?

  

  

  

![](https://link.nylas.com/open/7gh2noqketazj3w6cplb9vxl3/local-a86aeb96-d05e?
r=cmVwbHkrMDAwM2I4NTE2MTM1YzViOWM1Mzg4MjgwZGJiYjlhMTJhYmFjMmNiY2E4OGFiOWEwOTJj
ZjAwMDAwMDAxMTQ5ZTNkZmM5MmExNjljZTBjMTQ2MWRiQHJlcGx5LmdpdGh1Yi5jb20=)

  
On Jan 23 2017, at 4:56 pm, jmehta8 <notifications@github.com> wrote:  

> Hi,  
On an attempt to install vpc, I followed the below instructions, but end up
getting error as described in

>

> install.packages("devtools")  
library("devtools")  
install_github("ronkeizer/vpc")  
library(vpc)

>

> Error

>

>   * installing _source_ package 'vpc' ...  
** R  
** data  
*** moving datasets to lazyload DB  
** inst  
** tests  
** preparing package for lazy loading  
Error in loadNamespace(j <\- i[[1L]], c(lib.loc, .libPaths()), versionCheck =
vI[[j]]) :  
there is no package called 'e1071'  
Error : package 'classInt' could not be loaded  
ERROR: lazy loading failed for package 'vpc'

>   * removing 'C:/R-3.3.2/library/vpc'  
Error: Command failed (1)

>

> Kindly correct if I missed anything while installing.

>

> Thank you,  
~J

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly, [view it on GitHub](https://github.com/ronkeizer
/vpc/issues/35&r=cmVwbHkrMDAwM2I4NTE2MTM1YzViOWM1Mzg4MjgwZGJiYjlhMTJhYmFjMmNiY
2E4OGFiOWEwOTJjZjAwMDAwMDAxMTQ5ZTNkZmM5MmExNjljZTBjMTQ2MWRiQHJlcGx5LmdpdGh1Yi5
jb20=), or [mute the thread](https://github.com/notifications/unsubscribe-auth
/AAO4UWh7c6iiDZdc48c-ze4-fD8DQH6Nks5rVSH8gaJpZM4LrmE1&r=cmVwbHkrMDAwM2I4NTE2MT
M1YzViOWM1Mzg4MjgwZGJiYjlhMTJhYmFjMmNiY2E4OGFiOWEwOTJjZjAwMDAwMDAxMTQ5ZTNkZmM5
MmExNjljZTBjMTQ2MWRiQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notificat
ions/beacon/AAO4UWa31r09jSsg9fhfyG0kPrzfu6hdks5rVSH8gaJpZM4LrmE1.gif)

**Comment by jmehta8** [comment]
Worked. Thank you prompt response.
