### ISSUE TITLE
ULOQ and LLOQ behavior for continuous VPCs

### ISSUE THREAD

**Issue by guiastrennec** [ronkeizer/vpc#43]
I would like to debate over the way LLOQ (and ULOQ) are implemented for continuous VPCs. 

Here is an example of VPC for continuous data without LLOQ: 
![vpc_base](https://user-images.githubusercontent.com/7304883/29432499-3ab023ca-839c-11e7-92bb-1eda387d9229.png)

Now if a LLOQ is defined in `vpc(obs, sim, lloq = 20)` all data below LLOQ is like cut from the plot as shown below:
![vpc_lloq_cut](https://user-images.githubusercontent.com/7304883/29432516-464d34d4-839c-11e7-950a-83dde928b931.png)

I believe that it would be more informative to have the following instead:
![vpc_lloq_2](https://user-images.githubusercontent.com/7304883/29432711-f42ef6a0-839c-11e7-996f-7a96f5e1a546.png)

Which as in xpose4 could be used along with the `vpc_cens(obs, sim, lloq = 20)` to ensure proper prediction of the proportion of BQL data:
![vpc_cens](https://user-images.githubusercontent.com/7304883/29432800-38ad7d92-839d-11e7-8619-27a105b8bc8e.png)

Let me know your thoughts!

**Comment by ronkeizer** [comment]
hi Ben,

I'm not so sure. I can see your point in a simulation scenario where you
indeed have all the values of the censored observations, then the plot you
propose is surely more informative. However, the most common use-case (and
what this functionality is meant for) is that you don't have the underlying
value of the censored data. Since with the VPC we are trying to see whether
our simulated data match up with our observed data, I would say we don't
want our stats of the simulation data to incorporate any censored data
either?
We could add the LOQ line with a label in the plot as you did though, to
indicate that there is an LOQ?

R

**Comment by andrewhooker** [comment]
Hi Benjamin,

I think that we do this right in xpose4. You cannot compute the real percentiles when they go below/above the LOQ but you can always compute the simulated values.

Andy

**Comment by andrewhooker** [comment]
I think like this makes sense.

**Comment by guiastrennec** [comment]
@ronkeizer I may have gotten a bit confused throughout my explanation, the point I was trying to make is to have it as in xpose4. I would recommend the following for continuous VPCs:

1. As mentioned by @andrewhooker only the simulations should be shown below the LLOQ (or above the ULOQ).
2. I would use `NA` values and not LLOQ for the lines of the observation percentiles, which to me are misleading if they are flat at LLOQ.
3. Add an horizontal line at LLOQ on the plot

**Comment by ronkeizer** [comment]
Ok, understand now and makes sense. My thinking got a bit sidetrack by the plot you showed with the obs-line going below loq too. Let me check how xpose 4 is showing this exactly and get back to you.

________________________________

**Comment by andrewhooker** [comment]
I can look into this if you like.

**Comment by ronkeizer** [comment]
Sure, sounds good. It shouldn't be a large change in my code, I think.
