### ISSUE TITLE
The documentation `vpc.ronkeizer.com` is down

### ISSUE THREAD

**Issue by intiben** [ronkeizer/vpc#85]
I am getting the following page when trying to access the vpc documentation (http://vpc.ronkeizer.com/):

<img width="512" alt="Screenshot 2022-12-06 at 13 24 39" src="https://user-images.githubusercontent.com/56064362/205911886-5d3ec05a-5e01-46df-88f5-392f65845e6d.png">

As a side note the documentation appeared to use http and not https.

**Comment by mhismail** [comment]
Hi @ronkeizer and @intiben, 

I created a mirror of the VPC docs hosted at the link below (hope it's OK, it's just nice to have the docs online since we teach this package).

https://vpc.gitbook.io/vpc-docs-1/

I attributed all credit to Ron in the forked repo, but if at any point you'd like me to take it down, let me know.

Thanks!

**Comment by ronkeizer** [comment]
Thanks Mohamed for providing the mirror, just saw this now. I'll get it up again as soon as possible, will let you know once it's up.

**Comment by ronkeizer** [comment]
The documentation is up again at vpc.ronkeizer.com, being served from this github repo from the new `/docs` folder. Mirrors can be shut down, but feel free to keep up for a little longer if pointing to them in teaching materials.

Source of the docs is still in `ronkeizer/vpc-docs` repo. At some point I might change it into a pgkdown site and combine into the `vpc` repo, but this should work well enough for now.
