### ISSUE TITLE
References for simulation of VPC data

### ISSUE THREAD

**Issue by adcascone** [ronkeizer/vpc#95]
Hello,

Would it be possible to provide a reference for the way in which data are simulated via the sim_data() function? It would also be helpful to provide an example for the way in which this function works, if possible. In the reference manual (pg. 17), this function's arguments have "See example," but there is no example included.

![image](https://github.com/ronkeizer/vpc/assets/70408991/499bc503-3409-4f1e-8148-d8e918951a23)

Thanks,
Arianna

**Comment by roninsightrx** [comment]
hi Arianne,
The `sim_data` functionality is just a general-purpose simulation function where the user brings their own simulation function, parameter vector, and between-subject variability (omega_mat). To be honest, I have not used it myself in quite some time, as I commonly rely on simulations directly from PKPDsim, NONMEM, or nlmixr2. But you're right, it should have a better description and an example. Will add that soon.
Thanks for highlighting this omission!

**Comment by roninsightrx** [comment]
Actually, on second thought, I am going to remove the sim_data() functionality altogether. Since this function is just a very crude simulation wrapper, it is not useful to have it in the VPC package. I'd like to adhere to the philosophy that a package should do very well what it really needs to do, and not do other stuff in a mediocre way. As you know there are very good packages available for simulation (PKPDsim, mrgsolve, rxode etc), so there is no need to have any of that available natively in vpc. It would also cost time to support a sim_data() functionality properly in this package. 
Thanks again!

**Comment by adcascone** [comment]
Thanks for your thoughtful replies!

**Comment by adcascone** [comment]
Hi again Ron,

Are there plans to update the version of the vpc package that's available on CRAN to reflect the changes that have been implemented in this package since January 2021? 

Thanks for your time,
Arianna
